apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rc0s8rf24-python
  janus-idp.io/tekton: rc0s8rf24-python
  backstage.io/kubernetes-id: rc0s8rf24-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: rc0s8rf24-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
