apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rc0s8rf24-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rc0s8rf24-python 
  name: rc0s8rf24-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rc0s8rf24-python 
